import Head from "next/head";
import Link from "next/Link";
import styles from "../styles/Home.module.scss";

export default function Home({ author }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Sobre o sistema</h1>

        <p>
          O Projeto foi desenvolvido junto ao video do Bonieky Lacerda, para
          demonstrar os primeiros passos do Framework Next.js
        </p>

        <p>Autor: {author}</p>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      author: "Bonieky",
    },
  };
}
